# Generated by Django 5.2.5 on 2025-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor',
            new_name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
